### ISSUE TITLE
`Install-PsResource` throws on a fresh new system

### ISSUE THREAD

**Issue by Jawz84** [PowerShell/PSResourceGet#178] opened 2020-07-12 20:32 UTC
# context

I just installed Windows 10 from a version 2004 disk image from Microsoft. I installed `pwsh` and installed the new `powershellget` module (Beta 6).

```text
PS C:\Users\joskw> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Script     3.0.0      beta6      PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceR…
Script     2.0.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …
```

```text
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# steps to reproduce

```text
PS C:\Users\joskw> Install-PSResource -Name az
Install-PSResource: Could not load file or assembly 'System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
PS C:\Users\joskw> get-error

Exception             :
    Type       : System.IO.FileNotFoundException
    Message    : Could not load file or assembly 'System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    FileName   : System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    TargetSite :
        Name          : ProcessRecord
        DeclaringType : Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource
        MemberType    : Method
        Module        : PowerShellGet.dll
    StackTrace :
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : PowerShellGet
    HResult    : -2147024894
CategoryInfo          : NotSpecified: (:) [Install-PSResource], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 11
    Line             : Install-PSResource -Name az
    PositionMessage  : At line:1 char:1
                       + Install-PSResource -Name az
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

I am now manually installing the NuGet package for System.Security.Principal.Windows, by running: `Install-Package System.Security.Principal.Windows`, but this seems to take forever due to some timeouts in the background or something. Will update later.

**Comment by Jawz84** [comment] 2020-07-12 20:38
Update after trying to manually install `System.Security.Principal.Windows`:
Alas, no luck.

```text
PS C:\Users\joskw> Install-Package System.Security.Principal.Windows -MinimumVersion 5.0.0 -Force
Install-Package: No match was found for the specified search criteria and package name 'System.Security.Principal.Windows'. Try Get-PackageSource to see all available registered package sources.

PS C:\Users\joskw> Install-Package System.Security.Principal.Windows -MinimumVersion 4.7.0 -Force                                                                                                                                               Name                           Version          Source           Summary
----                           -------          ------           -------
Microsoft.NETCore.Platforms    3.1.1            nuget.org        Provides runtime information required to resolve targ…
Microsoft.NETCore.Targets      3.1.0            nuget.org        Provides supporting infrastructure for portable proje…
System.Runtime                 4.3.1            nuget.org        Provides the fundamental primitives, classes and base…
System.Collections             4.3.0            nuget.org        Provides classes that define generic collections, whi…
System.Globalization           4.3.0            nuget.org        Provides classes that define culture-related informat…
System.Text.Encoding           4.3.0            nuget.org        Provides base abstract encoding classes for convertin…
System.Threading.Tasks         4.3.0            nuget.org        Provides types that simplify the work of writing conc…
System.IO                      4.3.0            nuget.org        Provides base input and output (I/O) types, including…
System.Reflection.Primitives   4.3.0            nuget.org        Provides common enumerations for reflection-based lib…
System.Reflection              4.3.0            nuget.org        Provides types that retrieve information about assemb…
System.Resources.ResourceMana… 4.3.0            nuget.org        Provides classes and attributes that allow developers…
System.Runtime.Extensions      4.3.1            nuget.org        Provides commonly-used classes for performing mathema…
System.Security.Principal      4.3.0            nuget.org        Provides the base interfaces for principal and identi…
System.Security.Claims         4.3.0            nuget.org        Provides classes that implement claims-based identity…
Microsoft.Win32.Primitives     4.3.0            nuget.org        Provides common types for Win32-based libraries.…
System.Diagnostics.Debug       4.3.0            nuget.org        Provides classes and attributes that allows basic int…
System.Runtime.Handles         4.3.0            nuget.org        Provides base classes, including System.Runtime.Inter…
System.Runtime.InteropServices 4.3.0            nuget.org        Provides types that support COM interop and platform …
System.Threading               4.3.0            nuget.org        Provides the fundamental synchronization primitives, …
System.Security.Principal.Win… 4.7.0            nuget.org        Provides classes for retrieving the current Windows u…

PS C:\Users\joskw> Install-PSResource az
Install-PSResource: Could not load file or assembly 'System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

**Comment by SydneyhSmith** [comment] 2020-07-16 22:53
Thanks @Jawz84 we have identified the issue, and should be resolved in the next release (should be out this week)

**Comment by Jawz84** [comment] 2020-07-17 05:23
That's awesome, thanks Sydney!

**Comment by rkeithhill** [comment] 2020-07-18 19:43
Great! I just ran into the same issue today trying to use `Update-PSResource`.

**Comment by ThomasNieto** [comment] 2020-08-10 04:38
I'm not able to reproduce this anymore on beta 8.

**Comment by Jawz84** [comment] 2020-08-10 11:43
Thank you @ThomasNieto. I am on vacation without my computer, can't confirm at this time. I'll take your word for it and reopen an issue in the future if necessary. 👍

#closes #

178

Met vriendelijke groet,

Jos Koelewijn

________________________________

**Closed as completed** 2020-08-13 22:31 UTC
Labels: Issue-Bug, Resolved-3.0, Area-Install
