### ISSUE TITLE
Support concurrent Install-PSResource and Save-PSResource

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSResourceGet#451] opened 2021-08-07 00:36 UTC
Whether a single meta-module like `Az` or using `-RequiredResource`, we should allow for concurrent install/save instead of doing it serially

**Comment by ThomasNieto** [comment] 2022-01-02 22:21
Duplicate of https://github.com/PowerShell/PowerShellGet/issues/69

**Closed as completed** 2022-04-26 16:50 UTC
Labels: Issue-Enhancement
