### ISSUE TITLE
Installing a module that is only prerelease without `-prerelease` switch quietly fails

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSResourceGet#1025] opened 2023-03-28 20:58 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

 ```powershell
install-psresource powershellai
```

### Expected behavior

```console
Since this module only has a prerelease version (version is < 1.0), it should provide an error that no module was found.  Even better would be an error indicating a prerelease was available but requires the `-prerelease` switch.
```

### Actual behavior

```console
PS> install-psresource powershellai

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its Trusted value by running the Set-PSResourceRepository cmdlet. Are you sure
you want to install the PSResource from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PS>
```

### Error details

```console
No error
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.19     beta19     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}


Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by alerickson** [comment] 2023-05-16 02:36
If a version is less than 1.0 we still consider it a stable version, NuGet does the same (via CLI and via brower UI).

As of beta21, powershellai installs without the -Prerelease parameter w/o errors.

**Comment by alerickson** [comment] 2023-05-19 22:42
Closing this issue as we've discussed this as expected behavior since we don't support semantic versioning.

**Closed as completed by alerickson** 2023-05-19 22:42 UTC
Labels: Issue-Bug, Area-Install
