### ISSUE TITLE
Uninstall doesn't take version from pipeline 

### ISSUE THREAD

**Issue by schittli** [PowerShell/PSResourceGet#1058] opened 2023-04-14 22:12 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

1. Make sure, you have two versions of one PS Module, e.g:
```
Get-Module -ListAvailable -Name 'Microsoft.Graph.Applications' | Select ModuleType, Version, Name

ModuleType Version Name
---------- ------- ----
    Script 1.25.0  Microsoft.Graph.Applications
    Script 1.9.6   Microsoft.Graph.Applications
```
2. Get the old Module in a Variable
```
$OldModule = Get-Module -ListAvailable -Name 'Microsoft.Graph.Applications' | ? Version -eq '1.9.6'
```
3. Validate
```
$OldModule | Select  ModuleType, Version, Name

ModuleType Version Name
---------- ------- ----
    Script 1.9.6   Microsoft.Graph.Applications
```
4. Uninstall the old Module
```
$OldModule | Uninstall-Module -Verbose
VERBOSE: Performing the operation "Uninstall-Module" on target "Version '1.25.0' of module 'Microsoft.Graph.Applications'".
```
### Environment data

```powershell
$PSVersionTable | ft

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

The same issues:
$PSVersionTable | ft

Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ThomasNieto** [comment] 2023-04-17 18:58
@schittli have you tried PowerShellGet v3 beta to see if the issue is still present?

**Comment by alerickson** [comment] 2023-05-16 00:33
Closing this issue as it is not reproducible in 3.0.21-beta21

**Closed as completed by alerickson** 2023-05-16 00:33 UTC
Labels: Issue-Bug, Area-Uninstall
