### ISSUE TITLE
Better handling for "multiple modules matched"

### ISSUE THREAD

**Issue by Pxtl** [PowerShell/PSResourceGet#621] opened 2022-03-25 23:00 UTC
### Summary of the new feature / enhancement

We're trying to set up a private PSRepository to store custom PS modules *and* to whitelist modules obtained from PSGallery.

However, if a module is present on both PSGallery and our private repo, then you hit the `multiple modules matched` error must manually specify which source to fetch the module from using `-repository`.  This works for very locked down machines, but since the `Get-PSRepository` list is managed in userland it's going to be very difficult to keep it in sync for all users and provide some top-down, especially when some of our developers are fully external and not developing on managed machines.

That means installing our private whitelisting repo will actually *break* your ability to access modules that are on PSGallery, to the point you'll have to abandon PSGallery.  Yes, you can override it with `-repository` but this is a poor solution since it means all existing installer scripts are now broken too.

Ideally can we get some kind of priority setting for `Register-PSRepository` where we could say that our trusted whitelist repo is higher-priority than the untrusted `PSGallery`?  That instead of *failing* on name-collision, it should prefer the package available in the higher-priority PSrepository.

### Proposed technical implementation details (optional)

New parameter on `Register-PSRepository` called `-OrderIndex` that takes an int value that will be stored onto the `PSRepositoryInfo` object as a new member.  Where a name-collision occurs in `Install-Module`, the PSRepositoryInfo with the lower `OrderIndex` will be chosen as the source for this package.  If two PSRepositoryInfos have the same OrderIndex, the previous behavior returns, but with a message noting the identical `OrderIndex` and suggesting that changing it would resolve the issue.

If not specified, the default OrderIndex of 5 will be inferred, which PSGallery has by default as well.  This means existing behavior is preserved if the new feature is not used, as all PSRepositoryInfos will effectively have a value of 5 unless otherwise specified which means they will all continue to conflict on name-collisions.

Example use: 
```ps1
#register the PSGallery and fetch the module for our whitelist.
Register-PSRepository -Default -ErrorAction SilentlyContinue
Install-Module ReportingServicesTools

#register the internal whitelist and push the module to it
Register-PSRepository internal `
    -SourceLocation https://myazuredevops.example.com/myorg/_packaging/Packages/nuget/v2 `
    -PublishLocation https://myazuredevops.example.com/myorg/_packaging/Packages/nuget/v2 `
    -InstallationPolicy Trusted `
    -OrderIndex 1
Publish-Module -Name ReportingServicesTools -Repository internal -NuGetApiKey 'dummy NuGetApiKey'

#now reinstall the module
Install-Module ReportingServicesTools -Force
```

Without the `-OrderIndex` feature, the above script would fail because it's present in both repos.  Now, since we have a higher priority PSRepositoryInfo with a lower OrderIndex, it will sucessfully read from "internal".

**Comment by alerickson** [comment] 2022-03-28 02:39
Hi @Pxtl, this has been a complaint we've received a lot with versions 2.x.x and below.  Note that this repository is for the rewrite of PowerShellGet (versions 3.0.0 and up).  In this repo we've done our best to address this issue by adding a `-Priority` parameter to the `Register-PSResourceRepository` cmdlet (which is replacing `Register-PSRepository`).

Could you test out our preview version ([3.0.0-beta12](https://www.powershellgallery.com/packages/PowerShellGet/3.0.12-beta)) and let us know if this satisfies your needs?  If not, we can work on adding features or modifying this repository to make it work for your scenario!  Since this is a new feature, we'd love to get some feedback on this!

**Comment by Pxtl** [comment] 2022-03-28 13:23
Oh!  I'm sorry, I didn't realize there was a separate repo for PowerShellGet 2.

**Comment by alerickson** [comment] 2022-03-28 23:58
@Pxtl no worries [PowerShellGetv2](https://github.com/powershell/powershellgetv2) is the repo for issues with 2.x.x and below, but this would be the correct repo for any feature requests 😃

**Comment by SydneyhSmith** [comment] 2022-03-31 18:07
Closing as this is resolved in v3....will open if this is still reproducing

**Closed as completed by SydneyhSmith** 2022-03-31 18:07 UTC
Labels: feature_request, Resolution-Fixed
