### ISSUE TITLE
Cmdlets do not have PassThru parameter

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#158] opened 2020-06-14 22:25 UTC
`*-Resource` and `*-ResourceRepository` cmdlets should have a `PassThru` parameter for resource and resource repository information.

**Comment by SydneyhSmith** [comment] 2020-06-18 22:53
thanks @ThomasNieto this is a dupe of #132

**Closed as completed** 2020-06-18 22:53 UTC
Labels: feature_request
