### ISSUE TITLE
Several issues with 3.0

### ISSUE THREAD

**Issue by wekempf** [PowerShell/PSResourceGet#113] opened 2020-04-13 14:57 UTC
I realize this is preview, but it doesn't seem to be usable at all (or I *really* don't understand the new commands). I ran "Install-PSResource z", which reported success. However "Get-PSResource z" returns null. "Update-PSResource z" reports an error "Update-PSResource: Value cannot be null. (Parameter 'path')", despite the fact that "help Update-PSResource" and tab completion agree that 'path' isn't a valid parameter. Running 'Install-PSResource z" a second time reports "Install-PSResource: Cannot create a file when that file already exists.", which I guess makes sense if we've already installed, but "Uninstall-PSResource z" reports "Uninstall-PSResource: Could not find a part of the path 'C:\Program Files\PowerShell\Modules'."

The documentation for these new commands don't seem to be documented, as help gives no description and only reports the syntax and parameters (also sans description). So it is very possible I'm just not understanding these new commands, but if that's the case they seem to stray quite far from their PowerShellGet 2.0 "equivalents".

**Comment by SydneyhSmith** [comment] 2020-04-16 22:38
@wekempf thanks for opening this issue, the issue you are hitting is not expected and we are having trouble reproducing it. It doesnt help that because we havent implemented error messages yet, so it is difficult to determine the root cause however some information about your system would be useful could you please provide: 
```powershell
> $PSVersionTable

```

```powershell
> (get-command find-psresource).Module.ModuleBase

```

**Comment by wekempf** [comment] 2020-04-20 20:20
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> (get-command find-psresource).Module.ModuleBase
C:\Users\XXX\Documents\PowerShell\Modules\PowerShellGet\3.0.0

That doesn't look right?

**Comment by SydneyhSmith** [comment] 2020-04-23 22:51
@wekempf thanks for the additional info, nothing about your set-up looks wrong...unfortunately we wont have error handling/error messaging in until the next release but likely what is happening is that an error is being thrown at some point but you are not getting the proper feedback back on that....once we have error messaging in the next release we should be able to better diagnose this issue

**Comment by SydneyhSmith** [comment] 2020-09-08 16:06
Closing this issue as resolved (based on improved install functionality, error messaging, and verbose)...thanks for your patience on this

**Closed as completed by SydneyhSmith** 2020-09-08 16:06 UTC
Labels: Needs-Repro-Info
