### ISSUE TITLE
Feature request: Enable updating all modules

### ISSUE THREAD

**Issue by iricigor** [PowerShell/PSResourceGet#174] opened 2020-07-09 09:00 UTC
As this is sill early in development, I would like to propose one possible extension that might bring big benefits.

Consider enabling functionality that will find or update all local PS modules. Here is [one possible implementation example](https://github.com/iricigor/psaptgetupdate/blob/db81ea883c7505bbe7a047bab70fe2aa37593f56/Public/Update-ModuleFromCache.ps1#L26) in POC I did in 2018. Since search will be done in local cache, the only time consuming operation would be to list currently loaded or installed modules.

It can be implemented either as standalone command or as extension to `Find-PSResource` or `Update-PSResource`, something like:
```PowerShel
Find-PSResource -ListUpdatable
Update-PSResource * 
```

I am not sure on what's the best syntax setup. But, I believe a functionality to find all updatable resources is one of the common functionalities in modern package managers, and PowerShellGet 3 should have it. 

Keep up the good work!

**Comment by SydneyhSmith** [comment] 2020-07-16 22:58
Thanks @iricigor that sounds cool, we are going investigate whether we can make this happen in the 3.0 timeframe or if it will fall after?

**Comment by SydneyhSmith** [comment] 2020-08-25 18:55
Current workaround would be something like: Get-PSResource * |Update-PSResource 
Going to mark this as Consider 3.0

**Comment by SydneyhSmith** [comment] 2020-09-08 19:11
Marking this as a duplicate of #157

**Closed as completed by SydneyhSmith** 2020-09-08 19:11 UTC
Labels: Area-Update, feature_request
