### ISSUE TITLE
Local repository returns 4 digit version when 2 or 3 digit is in use

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#1093] opened 2023-05-08 20:31 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Create a local repository and save a few packages with a 2 or 3 digit version number. Then try running `Find-PSResource` and you'll notice that `0` get added.

### Expected behavior

```console
Find-PSResource AnyPackage -Repository Local

Name       Version Prerelease Repository Description
----       ------- ---------- ---------- -----------
AnyPackage 0.1.0              Local      Use various package managers with a single set of commands.
```

### Actual behavior

```console
Find-PSResource AnyPackage -Repository Local

Name       Version Prerelease Repository Description
----       ------- ---------- ---------- -----------
AnyPackage 0.1.0.0            Local      Use various package managers with a single set of commands.
```

### Environment data

```powershell
beta20
7.4-preview3
```

**Comment by hanpq** [comment] 2023-05-12 12:49
Noticed this as well today. It is not restricted to local repos, I'm seeing the same issue on packages from a Proget/Nuget instance.

The package defines a 3 digit version number however Find-PSResource appends a forth digit, revision 0.

Once installed Get-PSResource shows 3 digits correctly. I think Find-PSResource incorrectly parses revision = -1 (undefined) as  0 (defined)

**Comment by alerickson** [comment] 2023-05-23 20:55
@hanpq do you have some examples (names and versions).  I haven't been able to repro this locally but I'm testing with the latest local build

**Comment by hanpq** [comment] 2023-05-24 06:37
Sure, however I'm running 3.0.19 as Find-PSResource is broken in 20 and 21 due to the "Object reference not set to an instance of an object." #1054 

Hopefully this is already be solved in 21/22 but I cannot test it :)

``` powershell
Get-Module Pester -ListAvailable

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     5.4.1                 Pester                              Desk

```

``` powershell
Find-Module Pester

Version              Name                                Repository
-------              ----                                ----------
5.4.1                Pester                              PSGallery

```

``` powershell
Get-PSResource Pester

Name   Version Prerelease Repository
----   ------- ---------- ----------
Pester 5.4.1              PSGallery

```

``` powershell

Find-PSResource Pester

Name   Version Prerelease Repository
----   ------- ---------- ----------
Pester 5.4.1.0            PSGallery

```

**Comment by alerickson** [comment] 2023-05-24 20:43
Okay, so what's happening here is that the PowerShell Gallery looks at the .psd1 as the source of truth for versions (ignores the version in the nuspec), the NuGet Gallery (and I assume other .nupkg based repos) looks at the nuspec as the source of truth (of course packages may or may not have a module manifest).  Since find just accesses the package metadata to retrieve this info, we're stuck with using whatever the server determines is the version.

For local repositories, PSGet is using the module manifest as the source of truth and if there's no module manifest the nuspec version is used.  


@hanpq we're working on that fix and should have that resolved in the next month!

**Comment by alerickson** [comment] 2023-05-25 22:30
Also see related issue: #915

**Comment by alerickson** [comment] 2023-07-11 06:57
The Pester example in the third to last comment seems to be resolved now, I'm no longer able to repro.

Tried saving some 3 digit versions of packages into a local repository and calling `Find-PSResource` on them but this also no longer seems to be reproducing.  If this is still an issue with the release of PSResourceGet 0.5.23-beta23 feel free to comment again here or open a new issue.

**Closed as completed by alerickson** 2023-07-11 06:57 UTC
Labels: Issue-Bug, Area-Find
