### ISSUE TITLE
Uninstall-PSResource uninstalls module when some other module depends on it

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PSResourceGet#1303] opened 2023-07-27 16:54 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Install Az.Storage module. It depends on Az.Accounts. Then try to uninstall Az.Accounts.

```powershell
Find-PSResource -Name pester,az.storage -IncludeDependencies -Verbose
VERBOSE: Searching in repository PSGallery

Name        Version Prerelease Repository Description
----        ------- ---------- ---------- -----------
Pester      5.5.0              PSGallery  Pester provides a framework for running BDD style Tests to execute and validate PowerShell commands inside of PowerShel…
Az.Storage  5.8.0              PSGallery  Microsoft Azure PowerShell - Storage service data plane and management cmdlets for Azure Resource Manager in Windows Po…
Az.Accounts 2.12.4             PSGallery  Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in Windows PowerShell an…

Install-PSResource -Name az.accounts,pester,az.storage -Verbose

Uninstall-PSResource -Name az.accounts -Verbose
```

`Uninstall-PSResource -Name az.accounts -Verbose` should not uninstall the Az.Accounts module.

### Expected behavior

```console
Az.Accounts module should not be removed
```

### Actual behavior

```console
Uninstall-PSResource -Name az.accounts -Verbose
VERBOSE: Retrieving directories in the path '/home/aditya/.local/share/powershell/Modules'
VERBOSE: Retrieving directories in the path '/home/aditya/.local/share/powershell/Scripts'
VERBOSE: All paths to search: '/home/aditya/.local/share/powershell/Modules/Az.Storage'
VERBOSE: All paths to search: '/home/aditya/.local/share/powershell/Modules/Az.Accounts'
VERBOSE: All paths to search: '/home/aditya/.local/share/powershell/Modules/Pester'
VERBOSE: All paths to search: '/home/aditya/.local/share/powershell/Modules/Microsoft.PowerShell.PSResourceGet'
VERBOSE: Searching through package path: '/home/aditya/.local/share/powershell/Modules/Az.Accounts'
VERBOSE: Searching through package path: '/home/aditya/.local/share/powershell/Modules/Az.Accounts'
VERBOSE: Searching through package version path: '/home/aditya/.local/share/powershell/Modules/Az.Accounts/2.12.4'
VERBOSE: Package version parsed as NuGet version: '2.12.4'
VERBOSE: Performing the operation "Uninstall-PSResource" on target "Uninstall resource 'Az.Accounts', version '2.12.4', from path '/home/aditya/.local/share/powershell/Modules/Az.Accounts/2.12.4'".
VERBOSE: Successfully uninstalled 'Az.Accounts' from path '/home/aditya/.local/share/powershell/Modules/Az.Accounts/2.12.4'.
```

### Error details

```console
No error when error is expected
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     0.5.23     beta23     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}


Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SimonWahlin** [comment] 2023-07-27 17:18
I think this is a duplicate of #760

**Closed as completed** 2023-07-31 18:23 UTC
Labels: Resolution-Duplicate
